@isTest
private class CommunityTest2 {
/*Component Controllers Tests*/

	static testMethod void test_CommunityFeedNavigationController() {
		CommunityFeedNavigationController.test1();
	}

	static testMethod void test_CommunityFollowController() {
		CommunityFollowController.test1();
	}

	static testMethod void test_CommunityFeedController() {
		CommunityFeedController.test1();
	}

	static testMethod void test_CommunityTagDisplayController() {
		CommunityTagDisplayController.test1();
	}

	static testMethod void test_CommunityTagSelectorController() {
		CommunityTagSelectorController.test1();
	}

	static testMethod void test_CommunityMenuController() {
		CommunityMenuController.test1();
	}

	static testMethod void test_CommunityHomeComponentController() {
		CommunityHomeComponentController.test1();
	}

	static testMethod void test_CommunityShareController() {
		CommunityShareController.test1();
	}

	static testMethod void test_CommunityTopCategoriesController() {
		CommunityTopCategoriesController.test1();
	}
}